aliases:
  business & entrepreneurship: enterprise_b2b
  networking & career: education_talent
  academic & education: education_talent
  sustainability & health: climate_sustainability
  technology & research: enterprise_b2b
  deep_tech: enterprise_b2b
  career_and_venture: education_talent
  organisationen f√ºr den berufseinstieg: education_talent
  studentische projekte: education_talent
  social & diversity: education_talent
  culture & the arts: education_talent
