aliases:
  autonomous driving: autonomous_systems
  autonomous driving stacks: autonomous_systems
  reinforcement learning: ai_ml
  rl: ai_ml
  path planning: autonomous_systems
  vehicle control: autonomous_systems
  localization: autonomous_systems
  trajectory planning: autonomous_systems
  perception: autonomous_systems
  cubesats: aerospace_space
  bi-liquid propulsion: aerospace_space
  cryogenic systems: aerospace_space
  cryogenic rockets: aerospace_space
  rocket control: aerospace_space
  rocket control systems: aerospace_space
  microtunneling: infrastructure_hardware
  pipe-jacking: infrastructure_hardware
  startup incubation: software_platforms
  ai entrepreneurship lab: ai_ml
  deep learning: ai_ml
  computer vision: ai_ml
  nlp: ai_ml
